# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 17:55
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import Group


def create_groups(apps, schema_editor):
    teacher = Group(name="teacher")
    teacher.save()
    student = Group(name="student")
    student.save()


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
