# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0002_auto_20160911_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interact.Course'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
