# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0003_auto_20160911_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='concept',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Concept',
        ),
    ]
