# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0004_auto_20160912_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='question',
            name='feedback',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='solution',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
