# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 20:41
from __future__ import unicode_literals

from django.db import migrations


def add_questions(apps, schema_editor):
    Question = apps.get_model("interact", "Question")
    Flavor = apps.get_model("interact", "Flavor")

    Flavor(name='multiple choice', description='Choose the best answer.').save()
    Flavor(name='fill-in-the-blank', description='Type your answer in the box. If the answer is larger than 999,  you must include the appropriate commas.').save()
    Flavor(name='multi-select', description='Click on each answer that is correct.').save()

    Question(solution='800',
             title='300 + 500 = ',
             flavor=Flavor(pk=1),
             concept='addition',
             difficulty_level=3,
             possible_solutions='200|600|900|800'
             ).save()

    Question(solution='3',
             title='4 x _ = 12',
             flavor=Flavor(pk=2),
             concept='multiplication',
             difficulty_level=3,
             possible_solutions='3|3.0'
             ).save()

    Question(solution='2 x 8|4 x 4',
             title='Select all the multiplication facts that equal 16.',
             flavor=Flavor(pk=3),
             concept='multiplication',
             difficulty_level=3,
             possible_solutions='4 x 2|8 x 4|2 x 8|4 x 4'
             ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0006_question_possible_solutions'),
    ]

    operations = [
        migrations.RunPython(add_questions)
    ]
