# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 18:11
from __future__ import unicode_literals

from django.db import migrations


def more_questions(apps, schema_editor):
    Question = apps.get_model("interact", "Question")
    Flavor = apps.get_model("interact", "Flavor")

    Flavor(name='drag-and-drop', description='Drag the correct answer(s) to appropriate box(es).').save()
    Flavor(name='fraction-fill-in', description='Click each box that you want to be shaded').save()

    Question(solution='thousands:5,000|hundreds:5,500|tens:5,480',
             title='Round 5,475 to the following place values',
             flavor=Flavor(pk=4),
             concept='rounding',
             difficulty_level=3,
             possible_solutions='5,000|4,000|6,000|5,400|5,500|5,600|5,580|5,480|5,470'
             ).save()

    Question(solution='2',
             title='Shade in 1/2 of the boxes.',
             description='4',
             flavor=Flavor(pk=5),
             concept='fractions',
             difficulty_level=3,
             possible_solutions='2'
             ).save()

class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0007_auto_20160913_1541'),
    ]

    operations = [
        migrations.RunPython(more_questions)
    ]
