# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 12:00
from __future__ import unicode_literals

from django.db import migrations


def add_graph_question(apps, schema_editor):
    Question = apps.get_model("interact", "Question")
    Flavor = apps.get_model("interact", "Flavor")

    Flavor(name='graph', description='Using the data, complete the graph').save()

    Question(solution='apples:10,bananas:5,oranges:3,pears:7',
             title='Fill in the graph with the data given',
             flavor=Flavor(pk=6),
             concept='graph',
             difficulty_level=3,
             possible_solutions='apples:10,bananas:5,oranges:3,pears:7'
             ).save()

class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0008_auto_20160914_1311'),
    ]

    operations = [
        migrations.RunPython(add_graph_question)
    ]
