# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 18:43
from __future__ import unicode_literals

from django.db import migrations


def add_practice_questions(apps, schema_editor):
    Question = apps.get_model("interact", "Question")
    Flavor = apps.get_model("interact", "Flavor")

# multiple choice quesitons 3rd grade
    Question(solution='11 + 4 = 15',
             title='Which fact would help you solve 15 - _ = 11',
             flavor=Flavor(pk=1),
             concept='fact-families',
             difficulty_level=3,
             possible_solutions='11 - 4 = 7|11 + 4 = 15|15 + 11 = 26|15 + 4 = 19'
             ).save()

    Question(solution='56 ÷ _ = 7',
             title='Which fact would  56 ÷ 7 = 8 help you solve?',
             flavor=Flavor(pk=1),
             concept='fact-families',
             difficulty_level=3,
             possible_solutions='56 ÷ _ = 7|56 - _ = 49|7 x _ = 14|5 x 56 = _'
             ).save()

    Question(solution='2',
             title='What number could be placed in the blank to make this statement true:   435 > 4_6',
             flavor=Flavor(pk=1),
             concept='inequalities',
             difficulty_level=3,
             possible_solutions='2|5|9|3'
             ).save()

    Question(solution='<',
             title='What symbol could be placed in the blank to make this statement true:   1,035 _ 1,735',
             flavor=Flavor(pk=1),
             concept='inequalities',
             difficulty_level=3,
             possible_solutions='>|=|<'
             ).save()

    Question(solution='298',
             title='4,000 - 3,702',
             flavor=Flavor(pk=1),
             concept='subtraction',
             difficulty_level=3,
             possible_solutions='298|7,702|300|1,702'
             ).save()

    Question(solution='813',
             title='Kirby is making a treehouse with his friend. They think they are going to end up needing 1,760 nails. Right now they have 947 nails.  How many more do they need to get before they can finish the treehouse.',
             flavor=Flavor(pk=1),
             concept='subtraction',
             difficulty_level=3,
             possible_solutions='813|1,227|827|800'
             ).save()

    Question(solution='24',
             title="When Breanna's mom went to the store to get cupcakes for the class, she could not remember how many students there were. She knew that the class sat in groups of 4 and that there were 6 groups. How many cupcakes does Breanna's mom need to get?",
             flavor=Flavor(pk=1),
             concept='subtraction',
             difficulty_level=3,
             possible_solutions='18|24|10|30'
             ).save()

    Question(solution='$0.84',
             title="Trinity is at her school's bookfair and wants to buy a pencil and notebook. The pencil costs $0.99 and the notebook costs $3.17. If Trinity pays with $5.00, how much change will she receive?",
             flavor=Flavor(pk=1),
             concept='money',
             difficulty_level=3,
             possible_solutions='$1.83|$4.16|$0.84|$1.16'
             ).save()

    Question(solution='7:30 PM',
             title="Edison and Wyatt are going to see a movie that starts at 5:30 PM. If the movie lasts 2 hours, what time will their movie be over?",
             flavor=Flavor(pk=1),
             concept='time',
             difficulty_level=3,
             possible_solutions='5:32 PM|7:30 PM|3:30 PM|6:30 PM'
             ).save()

    Question(solution='14 days',
             title="Scott's family is going on a two-week vacation over the summer. How many days will he be gone?",
             flavor=Flavor(pk=1),
             concept='time',
             difficulty_level=3,
             possible_solutions='7 days|10 days|14 days|2 days'
             ).save()

# multiple choice quesitons 4th grade
    Question(solution='4,296,800',
             title="Choose the answer that shows four million, two hundred ninety-six thousand, eight hundred in standard form",
             flavor=Flavor(pk=1),
             concept='place value',
             difficulty_level=4,
             possible_solutions='4,200,896|4,296,008|4,000,296|4,296,800'
             ).save()

    Question(solution='ten thousands',
             title="What place value is the 4 in? 943,509.83",
             flavor=Flavor(pk=1),
             concept='place value',
             difficulty_level=4,
             possible_solutions='hundreds|tens|ten thousands|thousandths'
             ).save()

    Question(solution='32,719.4',
             title="Which number is greater than 32,719.29",
             flavor=Flavor(pk=1),
             concept='inequalities',
             difficulty_level=4,
             possible_solutions='32,719.4|30,719.29|32,710.58|32,719.148'
             ).save()

    Question(solution='4,234.96',
             title="Which number would round to 4,235?",
             flavor=Flavor(pk=1),
             concept='rounding',
             difficulty_level=4,
             possible_solutions='4,234.96|4,235.5|4,234.09|4,235.09'
             ).save()

    Question(solution='7 diveded by 8',
             title="Which statement is equivalent to 7/8?",
             flavor=Flavor(pk=1),
             concept='fractions',
             difficulty_level=4,
             possible_solutions='7 divided by 8|8 divided by 7|7 times 8|8 minus 7'
             ).save()

    Question(solution='0.09, 0.145, 0.34, 0.52, 1.63',
             title="Order these decimals from least to greatest. 0.34, 0.52, 0.145, 1.63, 0.09",
             flavor=Flavor(pk=1),
             concept='place value',
             difficulty_level=4,
             possible_solutions='0.09, 0.145, 0.34, 0.52, 1.63|0.52, 1.63, 0.34, 0.145, 0.09|1.63, 0.52, 0.34, 0.145, 0.09|0.145, 1.63, 0.09, 0.52, 0.34'
             ).save()

    Question(solution='>',
             title="Which symbol could be placed in the blank to make this statement true.  43.75 _ 43.7",
             flavor=Flavor(pk=1),
             concept='inequalities',
             difficulty_level=4,
             possible_solutions='>|=|<'
             ).save()

    Question(solution='24',
             title="Which is the least common multiple of 4, 6, and 8",
             flavor=Flavor(pk=1),
             concept='multiples',
             difficulty_level=4,
             possible_solutions='24|32|192|12'
             ).save()

    Question(solution='14',
             title="All the fourth grade classes at Jefferson Elementary school are going on a field trip to see a play.  There are 95 students and 15 adults going on the field trip. If 8 people can sit in each row at the theater, how many rows will Jefferson Elementary need?",
             flavor=Flavor(pk=1),
             concept='computation',
             difficulty_level=4,
             possible_solutions='14|12|13|15'
             ).save()

    Question(solution='2,916',
             title="Which would be the 7th term of this pattern: 4, 12, 36, 108, ...",
             flavor=Flavor(pk=1),
             concept='patterns',
             difficulty_level=4,
             possible_solutions='324|972|2,916|8,748'
             ).save()

# multiple choice quesitons 5th grade
    Question(solution='21',
             title="Which of the following numbers is composite?",
             flavor=Flavor(pk=1),
             concept='number characteristics',
             difficulty_level=5,
             possible_solutions='2|17|21|37'
             ).save()

    Question(solution='39.41, 39.35, 39.381',
             title="Which set of numbers will round to 39.4",
             flavor=Flavor(pk=1),
             concept='rounding',
             difficulty_level=5,
             possible_solutions='39.41, 39.35, 39.381|39.41, 38.35, 39.381|39.47, 39.33, 39.381|39.41, 39.35, 39.319'
             ).save()

    Question(solution='0.625',
             title="Which decimal is equivalent to 5/8",
             flavor=Flavor(pk=1),
             concept='division',
             difficulty_level=5,
             possible_solutions='0.6225|0.625|0.785|1.6'
             ).save()

    Question(solution='4, 82, 376, 710',
             title="Which of the following lists contains only even numbers",
             flavor=Flavor(pk=1),
             concept='number characteristics',
             difficulty_level=5,
             possible_solutions='4, 82, 376, 710|4, 82, 379, 710|5, 81, 377, 713|4, 85, 376, 717'
             ).save()

    Question(solution='14 - 9',
             title="Which would be the first step in solving the following problem? 9 ÷ 3(14 - 9) + 4",
             flavor=Flavor(pk=1),
             concept='order of operations',
             difficulty_level=5,
             possible_solutions='9 ÷ 3|14 - 9|3 x 14|19'
             ).save()

    Question(solution='a chord that goes through the center of the cirlce',
             title="Which of the following best describes the diameter of a circle?",
             flavor=Flavor(pk=1),
             concept='geometry',
             difficulty_level=5,
             possible_solutions='a chord that goes through the center of a circle|a line segment that connects two points on a circle|the distance from the middle of a circle to a point on a circle|the distance around a circle'
             ).save()

    Question(solution='obtuse',
             title="Which best describes an angle that measures 119°?",
             flavor=Flavor(pk=1),
             concept='geometry',
             difficulty_level=5,
             possible_solutions='acute|right|obtuse|straight'
             ).save()

    Question(solution='rhombus',
             title="Which geometric figure can best be describes as a parallelogram with four congruent sides?",
             flavor=Flavor(pk=1),
             concept='geometry',
             difficulty_level=5,
             possible_solutions='rhombus|rectangle|trapezoid|triangle'
             ).save()

    Question(solution='13cm',
             title="Mr. Winfield's class is conducting a science experiement to decide the optimal amount of water needed to grow a plant. Cecilia measured each of the plants today, their heights were: 14cm, 19cm, 10cm, 19cm, 13cm, 4cm, and 1cm. Which of the following is the median plant height?",
             flavor=Flavor(pk=1),
             concept='statistics',
             difficulty_level=5,
             possible_solutions='13cm|19cm|11cm|18cm'
             ).save()

    Question(solution='30',
             title="Which would be the 8th term of this pattern: 2, 3, 5, 8, 12, ...",
             flavor=Flavor(pk=1),
             concept='patterns',
             difficulty_level=5,
             possible_solutions='17|23|30|27'
             ).save()

# fill in the blank quesitons 3rd grade
    Question(solution='26,905',
             title="Write twenty-six thousand, nine hundred five in standard form.",
             flavor=Flavor(pk=2),
             concept='place value',
             difficulty_level=3,
             possible_solutions='26,905'
             ).save()

    Question(solution='60',
             title="While Jerrie and Linda were on the way to school, they counted the number of birds they each saw. Jerrie saw 39 birds and Linda saw 24 birds. About how many birds did they see together?",
             flavor=Flavor(pk=2),
             concept='estimation',
             difficulty_level=3,
             possible_solutions='60'
             ).save()

    Question(solution='3,117',
             title="5,200 - 2,083",
             flavor=Flavor(pk=2),
             concept='subtraction',
             difficulty_level=3,
             possible_solutions='3,117'
             ).save()

    Question(solution='32',
             title="8 x 4",
             flavor=Flavor(pk=2),
             concept='multiplication',
             difficulty_level=3,
             possible_solutions='32'
             ).save()

    Question(solution='8',
             title="How many vertices does a cube have?",
             flavor=Flavor(pk=2),
             concept='geometry',
             difficulty_level=3,
             possible_solutions='8'
             ).save()

# fill in the blank quesitons 4th grade
    Question(solution='14,601.8',
             title="Write fourteen thousand, six hundred one and eight tenths in standard form.",
             flavor=Flavor(pk=2),
             concept='place value',
             difficulty_level=4,
             possible_solutions='14,601.8'
             ).save()

    Question(solution='33,000',
             title="Round 32,957 to the nearest hundred.",
             flavor=Flavor(pk=2),
             concept='rounding',
             difficulty_level=4,
             possible_solutions='33,000'
             ).save()

    Question(solution='37,896',
             title="50,400 - 12,504",
             flavor=Flavor(pk=2),
             concept='subtraction',
             difficulty_level=4,
             possible_solutions='37,896'
             ).save()

    Question(solution='2,916',
             title="36 x 81",
             flavor=Flavor(pk=2),
             concept='multiplication',
             difficulty_level=4,
             possible_solutions='2,916'
             ).save()

    Question(solution='1',
             title="How many endpoints does a ray have?",
             flavor=Flavor(pk=2),
             concept='geometry',
             difficulty_level=4,
             possible_solutions='1'
             ).save()

# fill in the blank quesitons 5th grade
    Question(solution='2',
             title="What is the only even prime number?",
             flavor=Flavor(pk=2),
             concept='number characteristics',
             difficulty_level=5,
             possible_solutions='2'
             ).save()

    Question(solution='51,890',
             title="Round 51,890.37 to the nearest whole.",
             flavor=Flavor(pk=2),
             concept='rounding',
             difficulty_level=5,
             possible_solutions='51,890'
             ).save()

    Question(solution='326',
             title="5,216 ÷ 16",
             flavor=Flavor(pk=2),
             concept='division',
             difficulty_level=5,
             possible_solutions='326'
             ).save()

    Question(solution='33,288',
             title="438 x 76",
             flavor=Flavor(pk=2),
             concept='multiplication',
             difficulty_level=5,
             possible_solutions='33,288'
             ).save()

    Question(solution='90',
             title="How many degrees are in a right angle?",
             flavor=Flavor(pk=2),
             concept='geometry',
             difficulty_level=5,
             possible_solutions='90'
             ).save()

# multiple select quesitons 3rd grade
    Question(solution='529|483|503|457',
             title="Select all the numbers that would round to 500.",
             flavor=Flavor(pk=3),
             concept='rounding',
             difficulty_level=3,
             possible_solutions='529|483|503|457|425|550|562'
             ).save()

    Question(solution='2 x 8 = 16|16 ÷ 2 = 8',
             title="Select each fact that is in the same fact-family as 8 x 2 = 16.",
             flavor=Flavor(pk=3),
             concept='fact-families',
             difficulty_level=3,
             possible_solutions='2 x 8 = 16|16 ÷ 2 = 8|16 - 8 = 8|8 + 2 = 10'
             ).save()

    Question(solution='29|33|41',
             title="Select all the numbers that would be included in this pattern: 5, 9, 13, 17, 21, ...",
             flavor=Flavor(pk=3),
             concept='patterns',
             difficulty_level=3,
             possible_solutions='29|33|41|22'
             ).save()

    Question(solution='7 x 2|2 x 7',
             title="Select the two facts that show the commutative property.",
             flavor=Flavor(pk=3),
             concept='properties',
             difficulty_level=3,
             possible_solutions='7 x 2|2 x 7|3 x 1|8 x 1'
             ).save()

    Question(solution='6|7|8|9',
             title="Select all the digits that could be placed in the blank to make the statement true: 163 > 1_8.",
             flavor=Flavor(pk=3),
             concept='inequalities',
             difficulty_level=3,
             possible_solutions='0|1|2|3|4|5|6|7|8|9'
             ).save()

# multiple select quesitons 4th grade
    Question(solution='5,315|4,803|5,439',
             title="Select all the numbers that would round to 5,000.",
             flavor=Flavor(pk=3),
             concept='place value',
             difficulty_level=4,
             possible_solutions='5,315|4,803|5,439|4,157|4,205|5,555|5,627'
             ).save()

    Question(solution='128|512',
             title="Select all the numbers that would be included in this pattern: 4, 8, 16, 32, ...",
             flavor=Flavor(pk=3),
             concept='patterns',
             difficulty_level=4,
             possible_solutions='128|512|36|40|246'
             ).save()

    Question(solution='1 + (2 + 3) = (1 + 2) + 3|(1 x 2) x 3 = 1 x (2 x 3)',
             title="Select all the facts that demonstrate the associative property.",
             flavor=Flavor(pk=3),
             concept='properties',
             difficulty_level=4,
             possible_solutions='1 + (2 + 3) = (1 + 2) + 3|(1 x 2) x 3 = 1 x (2 x 3)|1 + (2 + 3) = 1 + (3 + 2)|(1 x 2) x 3 = 2 x 3'
             ).save()

    Question(solution='9 ÷ 3|12 ÷ 6|4 x 3|2 + 2',
             title="Select all the steps needed to solve 2 + 4(9 ÷ 3) ÷ 6",
             flavor=Flavor(pk=3),
             concept='order of operations',
             difficulty_level=4,
             possible_solutions='9 ÷ 3|12 ÷ 6|4 x 3|2 + 2|2 + 4|4 x 9|3 ÷ 6'
             ).save()

    Question(solution='octogon|decagon|heptagon',
             title="Select all the polygons with greater than five sides.",
             flavor=Flavor(pk=3),
             concept='geometry',
             difficulty_level=4,
             possible_solutions='octogon|decagon|heptagon|pentagon|quadrilateral'
             ).save()

# multiple select quesitons 5th grade
    Question(solution='2|17|37',
             title="Select all the prime numbers",
             flavor=Flavor(pk=3),
             concept='number characteristics',
             difficulty_level=5,
             possible_solutions='2|17|37|39|54|81|77'
             ).save()

    Question(solution='5,470.49|5,469.802',
             title="Select all the numbers that would round to 5,470.",
             flavor=Flavor(pk=3),
             concept='rounding',
             difficulty_level=5,
             possible_solutions='5,470.49|5,469.802|5,470.62|5,469.38|5,459.9'
             ).save()

    Question(solution='mean|median|mode',
             title="Select all the measures of center.",
             flavor=Flavor(pk=3),
             concept='statistics',
             difficulty_level=5,
             possible_solutions='mean|median|mode|range'
             ).save()

    Question(solution='9 ÷ 3|12 ÷ 6|4 x 3|2 + 2',
             title="Select all the steps needed to solve 2 + 4(9 ÷ 3) ÷ 6",
             flavor=Flavor(pk=3),
             concept='order of operations',
             difficulty_level=5,
             possible_solutions='9 ÷ 3|12 ÷ 6|4 x 3|2 + 2|2 + 4|4 x 9|3 ÷ 6'
             ).save()

    Question(solution='40°|84°|27°',
             title="Select all the acute angles",
             flavor=Flavor(pk=3),
             concept='geometry',
             difficulty_level=5,
             possible_solutions='40°|84°|27°|153°|82°'
             ).save()

# drag and drop quesitons 3rd grade
    Question(solution='ten thousands:90,000|thousands:90,000|hundreds:89,500|tens:89,530',
             title='Round 89,525 to the following place values',
             flavor=Flavor(pk=4),
             concept='rounding',
             difficulty_level=3,
             possible_solutions='90,000|80,000|90,000|89,000|89,500|89,600|89,520|89,530'
             ).save()

    Question(solution='addition:subtraction|subtraction:addition|multiplication:division|division:multiplication',
             title="Drag the inverse operation of each into the correct box",
             flavor=Flavor(pk=4),
             concept='inverse operations',
             difficulty_level=3,
             possible_solutions='addition|subtraction|multiplication|division'
             ).save()

    Question(solution='803 _ 830:<|324 _ 324:=|1,007 _ 107:>',
             title="Drag each symbol to a statement to make it true",
             flavor=Flavor(pk=4),
             concept='inequalities',
             difficulty_level=3,
             possible_solutions='>|=|<'
             ).save()

    Question(solution='thousands:9|ten thousands:3|tens:5|hundred thousands:7|hundreds:2|ones:4',
             title="Drag each digit to its correct place value using the number 739,254",
             flavor=Flavor(pk=4),
             concept='place value',
             difficulty_level=3,
             possible_solutions='0|1|2|3|4|5|6|7|8|9'
             ).save()

    Question(solution='less than:<|greater than: >|equal to:=|not equal to:≠',
             title="Drag each symbol to the correct term",
             flavor=Flavor(pk=4),
             concept='inequalities',
             difficulty_level=3,
             possible_solutions='>|=|<|≠'
             ).save()

# drag and drop quesitons 4th grade
    Question(solution='7th Term:1,074|8th Term:1,004|9th Term:924',
             title="Extend the following pattern: 1,284; 1,274; 1,254; 1,224; 1,184",
             flavor=Flavor(pk=4),
             concept='place value',
             difficulty_level=4,
             possible_solutions='1,134|1,074|1,004|924|834|734'
             ).save()

    Question(solution='sum:addition|difference:subtraction|product:multiplication|quotient:division',
             title="Drag each operation to its correct term",
             flavor=Flavor(pk=4),
             concept='vocabulary',
             difficulty_level=4,
             possible_solutions='addition|subtraction|multiplication|division'
             ).save()

    Question(solution='product:56|factor:8|operation:x',
             title="For the fact 7 x 8 = 56, drag each part to the correct term",
             flavor=Flavor(pk=4),
             concept='vocabulary',
             difficulty_level=4,
             possible_solutions='8|x|56'
             ).save()

    Question(solution='8.03 _ 8.3:<|32.4 _ 32.40:=|1.07 _ 1.007:>',
             title="Drag each symbol to a statement to make it true",
             flavor=Flavor(pk=4),
             concept='inequalities',
             difficulty_level=4,
             possible_solutions='>|=|<'
             ).save()

    Question(solution='thousands:6|thousandths:1|tens:4|tenths:3|millions:5|hundred thousands:0',
             title="Drag each digit to its correct place value using the number 5,076,249.381",
             flavor=Flavor(pk=4),
             concept='place value',
             difficulty_level=4,
             possible_solutions='0|1|2|3|4|5|6|7|8|9'
             ).save()

# drag and drop quesitons 5th grade
    Question(solution='equilateral:4in, 4in, 4in|scalene:2cm, 3cm, 4cm|isosceles:12m, 12m, 5m',
             title="Classify each set of side lengths of a triangle as equilateral, scalene, or isosceles",
             flavor=Flavor(pk=4),
             concept='geometry',
             difficulty_level=5,
             possible_solutions='4in, 4in, 4in|2cm, 3cm, 4cm|12m, 12m, 5m'
             ).save()

    Question(solution='ten thousands:0|thousandths:9|tens:7|tenths:8|ones:1',
             title="Drag each digit to its correct place value using the number 603,471.829",
             flavor=Flavor(pk=4),
             concept='place value',
             difficulty_level=5,
             possible_solutions='0|1|2|3|4|5|6|7|8|9'
             ).save()

    Question(solution='mean:the fair share of a set of data|median:the middle number in a set of data|mode:the most frequently occuring data point in a set of data|range:the spread of a set of data',
             title="Drag each definition to the correct term",
             flavor=Flavor(pk=4),
             concept='statistics',
             difficulty_level=5,
             possible_solutions='the spread of a set of data|the fair share of a set of data|the middle number in a set of data|the most frequently occuring data point in a set of data'
             ).save()

    Question(solution='prime:exactly two factors|composite:more than two factors',
             title="Drag each definition to the correct term",
             flavor=Flavor(pk=4),
             concept='number characteristics',
             difficulty_level=5,
             possible_solutions='exactly two factors|more than two factors'
             ).save()

    Question(solution='variable:x|variable expression:5 + x|open sentence:5 + x = 14',
             title='Drag each item to its correct description',
             flavor=Flavor(pk=4),
             concept='algebra',
             difficulty_level=5,
             possible_solutions='5 + x = 14|5 + x|x'
             ).save()

# fraction fill-in quesitons 3rd grade
    Question(solution='3',
             title='Shade in 3/4 of the boxes.',
             description='4',
             flavor=Flavor(pk=5),
             concept='fraction',
             difficulty_level=3,
             possible_solutions='3'
             ).save()

    Question(solution='2',
             title="Shade in 1/3 of the boxes.",
             description='6',
             flavor=Flavor(pk=5),
             concept='fraction',
             difficulty_level=3,
             possible_solutions='2'
             ).save()

    Question(solution='3',
             title="Shade in the sum of 2/6 + 1/6.",
             description='6',
             flavor=Flavor(pk=5),
             concept='fraction',
             difficulty_level=3,
             possible_solutions='3'
             ).save()

    Question(solution='1',
             title="Shade in the equivalent of 2/4 of the boxes.",
             description='2',
             flavor=Flavor(pk=5),
             concept='fraction',
             difficulty_level=3,
             possible_solutions='1'
             ).save()

    Question(solution='6',
             title="Shade a the difference between 7/8 and 1/8.",
             description='8',
             flavor=Flavor(pk=5),
             concept='fraction',
             difficulty_level=3,
             possible_solutions='6'
             ).save()

# fraction fill-in quesitons 4th grade
    Question(solution='6',
             title="Shade in an equivalent number of the boxes as 3/4.",
             description='8',
             flavor=Flavor(pk=5),
             concept='fraction',
             difficulty_level=4,
             possible_solutions='6'
             ).save()

    Question(solution='9',
             title="Shade in the sum of 4/9 and 1/3.",
             description='7',
             flavor=Flavor(pk=5),
             concept='fraction',
             difficulty_level=4,
             possible_solutions='9'
             ).save()

    Question(solution='7',
             title="Shade in difference between 5/6 and 1/4.",
             description='12',
             flavor=Flavor(pk=5),
             concept='fraction',
             difficulty_level=4,
             possible_solutions='7'
             ).save()

    Question(solution='1',
             title="Shade in an equivalent number of the boxes as 5/10.",
             description='2',
             flavor=Flavor(pk=5),
             concept='fraction',
             difficulty_level=4,
             possible_solutions='1'
             ).save()

    Question(solution='1',
             title="Shade in an equivalent number of the boxes as 3/12.",
             description='4',
             flavor=Flavor(pk=5),
             concept='fraction',
             difficulty_level=4,
             possible_solutions='1'
             ).save()


# graph quesitons 3rd grade
    Question(solution='yellow:9|green:3|blue:12|red:7',
             title='Use the data below to complete the graph.',
             description='Favorite Colors',
             flavor=Flavor(pk=6),
             concept='bar graph',
             difficulty_level=3,
             possible_solutions='yellow:9|green:3|blue:12|red:7'
             ).save()

    Question(solution='Soccer:14|Baseball:12|Archery:4|Football:8',
             title="Use the data below to complete the graph.",
             description='Favorite Sports',
             flavor=Flavor(pk=6),
             concept='bar graph',
             difficulty_level=3,
             possible_solutions='Soccer:14|Baseball:12|Archery:4|Football:8'
             ).save()

    Question(solution='Shirts:5|Shorts:3|Shoes:1',
             title="Use the data below to complete the graph.",
             description='How Much to Pack',
             flavor=Flavor(pk=6),
             concept='bar graph',
             difficulty_level=3,
             possible_solutions='Shirts:5|Shorts:3|Shoes:1'
             ).save()

    Question(solution='Mr. Mendez:24|Ms. Davis:22|Ms. Teigen:25',
             title="Use the data below to complete the graph.",
             description='Students in Each 3rd Grade Class',
             flavor=Flavor(pk=6),
             concept='bar graph',
             difficulty_level=3,
             possible_solutions='Mr. Mendez:24|Ms. Davis:22|Ms. Teigen:25'
             ).save()

    Question(solution='Chocolate:10|Vanilla:8|Strawberry:2',
             title="Use the data below to complete the graph.",
             description="Favorite Ice Cream Flavors in Ms. Trapp's Class",
             flavor=Flavor(pk=6),
             concept='bar graph',
             difficulty_level=3,
             possible_solutions='Chocolate:10|Vanilla:8|Strawberry:2'
             ).save()

# graph quesitons 4th grade
    Question(solution='Yes:9|No:13',
             title="Use the data below to complete the graph.",
             description='Do We Wear Glasses?',
             flavor=Flavor(pk=6),
             concept='bar graph',
             difficulty_level=4,
             possible_solutions='Yes:9|No:13'
             ).save()

    Question(solution='Giraffes:5|Peacocks:1|Zebras:8|Pandas:2',
             title="Use the data below to complete the graph.",
             description='Animals in the Zoo',
             flavor=Flavor(pk=6),
             concept='bar graph',
             difficulty_level=4,
             possible_solutions='Giraffes:5|Peacocks:1|Zebras:8|Pandas:2'
             ).save()

    Question(solution='Action:5|Comedy:2|Family:6',
             title="Use the data below to complete the graph.",
             description='Movie Party Genre',
             flavor=Flavor(pk=6),
             concept='bar graph',
             difficulty_level=4,
             possible_solutions='Action:5|Comedy:2|Family:6'
             ).save()

    Question(solution='Bus:18|Walk:1|Car:3',
             title="Use the data below to complete the graph.",
             description='How Do We Get To School?',
             flavor=Flavor(pk=6),
             concept='bar graph',
             difficulty_level=4,
             possible_solutions='Bus:18|Walk:1|Car:3'
             ).save()

    Question(solution='Math:6|Science:9|History:6|English:4',
             title="Use the data below to complete the graph.",
             description='Favorite Subjects',
             flavor=Flavor(pk=6),
             concept='bar graph',
             difficulty_level=4,
             possible_solutions='Math:6|Science:9|History:6|English:4'
             ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0009_auto_20160919_0700'),
    ]

    operations = [
        migrations.RunPython(add_practice_questions)
    ]
